sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - secure: "LCwkqeFNsxqleRcbxEPlUTORJuBCX+O8N5CizGm1DR6BktkgCzYt+/Dyj/t77U7PfKg28PnK3KcDe1c0c5+3FuxZnBXQfu2qMBQuoGIGyPOrTih2Em31CuMxEigK7WA9f30eXxMGJJuVEm0ShhGhlZVk1UYN3QpTcLg7E5s7XE775+T4DGVRFdiXVnotCWtetTARDCmHl29ylr10f4RKg2svqrChgjLYRX86uh9H0vQrxPBhnu648dVcd2tcuEwNSEtzzjICevhVzTcCLHDUxLf+gpgucuniy/dPRjN7tx4GYug09Y6Xpt3dAXy7eMSCgJF4mYPOZwkCczbNrzORWiNJdldtcV18ssE/h1/HqN2FfW56su4qQRSq6dLdNvxtskEPDGIuzsW2BjiLtGhL2HS2DxiTCDdSE/LHAnfBKnVpMumYulm5HyQOCj+Yusuqz4STPVC1RxmWZyquRb5Hdr4aEQCEYUtHnoF7T7KrKQoPvOH396iEbEwFYUKcXftsAyiR0bANd4zaDAs9d9gitEG7EVu3W3pJ88XZCpU20BQdq1XnYzCSB5tYdzWvk0TM9kFTppPExxo8ci/nX+5TK91iN0A/TWoGN2Hj0Q8ZbPkP0YCDZWz8dNyVbaXEfddc8adaB8UoBIZsDUGD8Z463gaoAby4FcvSf8+sgFlsR8g=" # DOCKER_USER
    - secure: "JAzV0ymarQ5EdwRJgLXCm471M+4JeG9UGhf+7pnpQS/LF3DPm+BKEqTRdVVFs2a7B5Hr3C3TbU+UHs7j26xdt8i7C/0TrFMJCMiCLLtAasdDjdGRgsM6qro4E/Esw0qYhWARWC964NEX96/yy93Yg+WGkatBBQ7lXj9wdn4jfdClpt9ARrkzI27//gCHvxyyXjJPfciM17KPWIYlzmeGAtfT19uOsvihEaBEmgQERIN74ZO1i409V/4zlGlNUL9ankosmAxpuO8oUROEo+/JYKTYlXbtKbqf4HJYmV5YOgX3HvcEyu06pomNDRzNigw2eGvztY+bSQCuAGdcpnWUPaS6lHKXDN/f0S79p1ReYTzTFBAixEHrKn2CamnpwWIpfqTPabX6ZFsqF4Bh9CDPFXq3/Q/6vyLu+OMU6Brxy2kUlOjwdCUVhGQRVSyDg/SWEBpdixU9svC3/nOG9nZ0NYYxuFq1wPFR/obD5I6FtlyDSbMzl6HHjx7eeA4oAEiwxvB+yUgoHNLchr2JZiaP9sWS7FXe6n3oWlGpHaUiE0ltwaDFVqfe7d4twxvdLRvRfy66PSjXCo5eJYbEbDSote12l5To1MYXJm1dY6wHDdyQ1Z+Uaqes5R7ivmca/Fmm/LdDG8Vs6JrlEXy74nNtlAkgne/WS6phCzqFTbhm190=" # DOCKER_PASS
    - secure: "FSQHUYE3F22KPZUahg73hAOvFO4jjtLnq+A40mqCJOAvpeFLkgJiSWv6e2+722vicyqcqJDuguv1vbgToF3blJGPGHmJymsU+Kq4Y+XZHa3q/oUd/Uca86sOw0/QpmbnrKsjGPZkV2NKNLD/9k0ya+BwhxniVh5zX35c2afJm5vLhVrQkFvaLCwrE8YyNgwG0soP5QVsm+L7fjvai60Wm5KhfUHnTsNDnmzh0RYNJSB35657FCukuen6sSlV1EvtKazxS5r6HLQlCGsgR1nemeBjAsJAhtf8M5HHg2oWUE1QrcRcNpqZr+RnaL1RZbB5m7emiSjxGeZNUAWDWQjgiaMCS5UbPbIea8ctazazZel8PThXwEWpWa4GgNJ8CXVTPMlZMw/7Galtjs3RL3LmW2JUaq6yfthoE79MK9SWsDPA6WUFdtVgRikxmJ9pTmtW6OwRjdOTRwFzjJ0eeFsmdEx+0MfcvJ3DDjGyGAFTQO33Q6fREIO8SbgQPacG9K5F+RaLvHfbBXyb4z7FGFHvRAtFFmpY28CUmGld2Xc+Y0WGjfFHxYNWyvF5vCfGVoFZhxIM+FQt4bc9jcNJhtdmVybtBdki705MMZeRJthIvYMsr8tO5bPTDjG/U81JqPCfOr/zLFFg36teDgknfROK39DbBbknkwN+7RWuaBEDUhU=" # AWS_ACCESS_KEY
    - secure: "AAsbYxqk/XgfuopH/dGitJMwbI771gAsYdmVBDcWCkPnqd+JnCBSs+qWh8AyNSylwoen9LfG7NtOQ/gmFQVKaifjlYEMbuJ8iWoJ1p9YPvst4P4GaIkDTAKKV619qbr2xJK7got6m/puQY2TK4owVCPvXRt5WzxPo7cRpvjzJGMEYb1Dw4uyaqQxDwbbcxosCUAteribG6l7KkeFkE9dIV34HiMel08IWig+ZWGK6fvVq73DXFBx9U4E0bx6/595gEw8Yy71tuiE23+x0TxHkjEgWnargZ3cpK5/Q2OGFlq3Ni2Hxgjy8GS3aV0U8IaYLMqoCwmvC9RFvBgovucRLFyGXpWCVi92RoUy8wQ1BVKwD0UKkSndavmf9/N10N98J3/ZdFLGyUR1AQPiMfFJGEH49Eu4D3I9ezZ3DvpyaDjttSkXAZ6ImQwdH1/VmR015QeVbUve8oaO14vrFY136dbNx7/iXV8ctz/uFpwWN6aL4zIatw+mT6a3xutLFZnjfV78l4wPaM7peaLOdmmXfr9HrsfA5KiY1lA4f5VGvn3ccZjse/nWxNvmAlwMbp+3qVKz7zTBxwdRLiYnN8Tx4nldb1oWIDKu9budIGLQQs9awpCBPRKlA2m0A3dwbZmUYgZ93o1NQ7eklWBxX7N4U3Uv+cpf7IbpBK3Ak266Xck=" # AWS_SECRET_KEY

addons:
  sonarcloud:
    organization: "vts-project"
    token:
      secure: "ZOk0WlVYSb72h1/B20fJsRhlk0xDAKpZYKKJSioSIwDeSw96ztueIyGTCls8Kj5ciR2I/dW78W/rN1pYLaLO553kMKCIMIBhyRQqTIS4hc2iIjzI37XChPuZzH2vTul1SZMftURLxpBcWnXKIsOSCcbP80bUM+9A4SqkNyynBkXTU7J6Q2sc0r70dYyHt7lWR8ytSol/Kp7VdKWNvKRpkC1A10ODQopCm0LuWyhtJNg0S9QDQdGxcBvUvSUafgqk4mAI8RdJZ34qr9oi+1aMfD4tM1aeM0VQBRYZlb8wvlWV72Zr3rmmDpfzwuR13Nbw3AyCtLg+FMzscqcUZHacVk5058pyNXUbarpP/59B0mWuwx2CvPAaM1SDAWbQglRioclix98jR8ox0wUzRg/QTRczkR2J9aX53wY7fEOxB9UQ97GsX9/Q1hgqZ1yTF62+uedzFBq6dZJh8Yz85rOj2Zu0m97FZpJjEJtykoHR2UhyX3rBAOc7FgsDL9MpTclSH8g5ChXlJtYihOEOY1+193ykQ12p/f9VpEtewU291cjdf6JeE4LeshGy4sHy3/XODIGxBPtCVacMM1BboJdYSWcbEIMCuON+NYB0sjXM03GBvanSaFtArbvNf9+mklo5Javvl4+algyFos1wVfeyp0Pl2YIK6GTWMJo2kK8y/p4="

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  
install: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ahmdgawad_vts-project -q -B -V -Dmaven.test.skip
  
  # CONFIG SERVICE
  - cd vts-configuration-server
  - docker build -t $DOCKER_USER/vts-configuration-server .
  - docker push $DOCKER_USER/vts-configuration-server

  # GATEWAY
  - cd ../vts-api-gateway
  - docker build -t $DOCKER_USER/vts-api-gateway .
  - docker push $DOCKER_USER/vts-api-gateway

  # EUREKA
  - cd ../vts-eureka-server
  - docker build -t $DOCKER_USER/vts-eureka-server .
  - docker push $DOCKER_USER/vts-eureka-server

  # CUSTOMER_SERVICE
  - cd ../vts-customer-service
  - docker build -t $DOCKER_USER/vts-customer-service .
  - docker push $DOCKER_USER/vts-customer-service

  # VEHICLE_SERVICE
  - cd ../vts-vehicle-service
  - docker build -t $DOCKER_USER/vts-vehicle-service .
  - docker push $DOCKER_USER/vts-vehicle-service

  # TRACKING_UI
  - cd ../vts-tracking-ui
  - docker build -t $DOCKER_USER/vts-tracking-ui .
  - docker push $DOCKER_USER/vts-tracking-ui
  - cd ..

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  region: "us-east-2"
  app: "vts-project"
  env: "VtsProject-env-2"
  bucket_name: "elasticbeanstalk-us-east-2-169742384670"
  bucket_path: "vts-project"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
