CREATE TABLE CUSTOMER_VS(
    CUST_ID INT PRIMARY KEY,
    CUST_FIRST_NAME VARCHAR(100) NOT NULL,
    CUST_LAST_NAME VARCHAR(100) NOT NULL,
    CUST_ADDRESS VARCHAR(255) NOT NULL
);

CREATE TABLE STATUS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	STATUS_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE VEHICLE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	VIN VARCHAR(255),
	REGISTRATION_NO VARCHAR(255),
	CUST_ID INT NOT NULL REFERENCES CUSTOMER_VS(CUST_ID),
	STATUS_ID INT NOT NULL REFERENCES STATUS(ID),
	LAST_UPDATED TIMESTAMP NOT NULL
);
